replicaCount: 1

image:
  repository: azureks.azurecr.io/gateway/shipengine-gateway
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: "shipengine-gateway"
fullnameOverride: "shipengine-gateway"

environment:
  environmentSecrets:
    - name: az-client-id
      key: AZURE_CLIENT_ID
    - name: az-client-secret
      key: AZURE_CLIENT_SECRET
    - name: az-tenant-id
      key: AZURE_TENANT_ID

probes:
  endpoints:
    liveness: "/api/health/alive"
    readiness: "/api/health/ready"
  initialDelay: 5
  interval: 15
  timeout: 240

serviceAccount:
  create: true
  name: "shipengine-gateway"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
resources:

  limits:
    cpu: 60m
    memory: 120Mi
  requests:
    cpu: 30m
    memory: 60Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 90
